using JeisAlive.Engine;
using JeisAlive.Models;

namespace JeisAlive.Forms;

public partial class MainForm : Form
{
    private readonly List<BoundFile> _boundFiles = new();
    private bool _outputPathAutoGenerated;

    public MainForm()
    {
        InitializeComponent();
        cboFormat.SelectedIndex = 0;
        cboFileAction.SelectedIndex = 0;
    }

    // ── Payload ─────────────────────────────────────────────────

    private void btnBrowsePayload_Click(object? sender, EventArgs e)
    {
        using var dlg = new OpenFileDialog
        {
            Title = "Select Payload",
            Filter = "Executable Files|*.exe|All Files|*.*"
        };

        if (dlg.ShowDialog() != DialogResult.OK) return;

        txtPayloadPath.Text = dlg.FileName;
        AutoGenerateOutputPath();
    }

    // ── Output ──────────────────────────────────────────────────

    private void btnBrowseOutput_Click(object? sender, EventArgs e)
    {
        string filter = cboFormat.SelectedIndex == 1
            ? "Batch Files|*.bat|All Files|*.*"
            : "Executable Files|*.exe|All Files|*.*";

        using var dlg = new SaveFileDialog
        {
            Title = "Save Output As",
            Filter = filter
        };

        if (dlg.ShowDialog() != DialogResult.OK) return;

        txtOutputPath.Text = dlg.FileName;
        _outputPathAutoGenerated = false;
    }

    private void cboFormat_SelectedIndexChanged(object? sender, EventArgs e)
    {
        if (_outputPathAutoGenerated && !string.IsNullOrEmpty(txtPayloadPath.Text))
        {
            AutoGenerateOutputPath();
        }
    }

    private void AutoGenerateOutputPath()
    {
        if (string.IsNullOrEmpty(txtPayloadPath.Text)) return;

        string dir = Path.GetDirectoryName(txtPayloadPath.Text) ?? "";
        string name = Path.GetFileNameWithoutExtension(txtPayloadPath.Text);
        string ext = cboFormat.SelectedIndex == 1 ? ".bat" : ".exe";

        txtOutputPath.Text = Path.Combine(dir, $"{name}_packed{ext}");
        _outputPathAutoGenerated = true;
    }

    // ── Binder ──────────────────────────────────────────────────

    private void btnAddFile_Click(object? sender, EventArgs e)
    {
        using var dlg = new OpenFileDialog
        {
            Title = "Add Bound Files",
            Filter = "All Files|*.*",
            Multiselect = true
        };

        if (dlg.ShowDialog() != DialogResult.OK) return;

        foreach (string path in dlg.FileNames)
        {
            _boundFiles.Add(new BoundFile
            {
                FilePath = path,
                Action = BoundFileAction.Open
            });
        }

        RefreshBoundFilesList();
    }

    private void btnRemoveFile_Click(object? sender, EventArgs e)
    {
        if (lstBoundFiles.SelectedIndices.Count == 0) return;

        // Remove in reverse order so indices stay valid
        var indices = new List<int>();
        foreach (int idx in lstBoundFiles.SelectedIndices)
            indices.Add(idx);

        indices.Sort();
        indices.Reverse();

        foreach (int idx in indices)
        {
            if (idx >= 0 && idx < _boundFiles.Count)
                _boundFiles.RemoveAt(idx);
        }

        RefreshBoundFilesList();
    }

    private void cboFileAction_SelectedIndexChanged(object? sender, EventArgs e)
    {
        if (lstBoundFiles.SelectedIndices.Count == 0) return;

        var action = (BoundFileAction)cboFileAction.SelectedIndex;

        foreach (int idx in lstBoundFiles.SelectedIndices)
        {
            if (idx >= 0 && idx < _boundFiles.Count)
                _boundFiles[idx].Action = action;
        }

        RefreshBoundFilesList();
    }

    private void lstBoundFiles_SelectedIndexChanged(object? sender, EventArgs e)
    {
        if (lstBoundFiles.SelectedIndices.Count == 0) return;

        int idx = lstBoundFiles.SelectedIndices[0];
        if (idx >= 0 && idx < _boundFiles.Count)
        {
            // Temporarily detach handler to avoid recursive update
            cboFileAction.SelectedIndexChanged -= cboFileAction_SelectedIndexChanged;
            cboFileAction.SelectedIndex = (int)_boundFiles[idx].Action;
            cboFileAction.SelectedIndexChanged += cboFileAction_SelectedIndexChanged;
        }
    }

    private void RefreshBoundFilesList()
    {
        lstBoundFiles.Items.Clear();
        foreach (var bf in _boundFiles)
        {
            var item = new ListViewItem(bf.FileName);
            item.SubItems.Add(bf.Action.ToString());
            lstBoundFiles.Items.Add(item);
        }
    }

    // ── Build ───────────────────────────────────────────────────

    private async void btnBuild_Click(object? sender, EventArgs e)
    {
        // Validate
        if (string.IsNullOrWhiteSpace(txtPayloadPath.Text) || !File.Exists(txtPayloadPath.Text))
        {
            MessageBox.Show("Payload file does not exist.", "Error",
                MessageBoxButtons.OK, MessageBoxIcon.Error);
            return;
        }

        if (string.IsNullOrWhiteSpace(txtOutputPath.Text))
        {
            MessageBox.Show("Output path is not set.", "Error",
                MessageBoxButtons.OK, MessageBoxIcon.Error);
            return;
        }

        // Prepare UI
        btnBuild.Enabled = false;
        txtLog.Clear();
        prgProgress.Value = 0;

        var config = new PackerConfig
        {
            PayloadPath = txtPayloadPath.Text,
            Format = cboFormat.SelectedIndex == 0 ? OutputFormat.NativeExe : OutputFormat.Batch,
            AntiDebug = chkAntiDebug.Checked,
            AntiVM = chkAntiVM.Checked,
            MeltFile = chkMelt.Checked,
            BoundFiles = new List<BoundFile>(_boundFiles),
            OutputPath = txtOutputPath.Text
        };

        try
        {
            await Task.Run(() =>
            {
                byte[] payloadBytes = File.ReadAllBytes(config.PayloadPath);

                var engine = new PackerEngine();
                engine.Log += msg => AppendLog(msg);

                AppendLog("[*] Starting build...");
                SetProgress(10);

                var (exeBytes, batContent) = engine.Package(payloadBytes, config);

                SetProgress(80);

                if (config.Format == OutputFormat.NativeExe)
                {
                    if (exeBytes == null || exeBytes.Length == 0)
                        throw new InvalidOperationException("Engine returned empty EXE output.");

                    File.WriteAllBytes(config.OutputPath, exeBytes);
                    AppendLog($"[+] Written {exeBytes.Length:N0} bytes to {config.OutputPath}");
                }
                else
                {
                    if (string.IsNullOrEmpty(batContent))
                        throw new InvalidOperationException("Engine returned empty batch output.");

                    File.WriteAllText(config.OutputPath, batContent);
                    AppendLog($"[+] Written batch file to {config.OutputPath}");
                }

                SetProgress(100);
                AppendLog("[+] Build complete!");
            });

            MessageBox.Show("Build complete!", "Success",
                MessageBoxButtons.OK, MessageBoxIcon.Information);
        }
        catch (Exception ex)
        {
            AppendLog($"[!] ERROR: {ex.Message}");
            MessageBox.Show($"Build failed:\n{ex.Message}", "Error",
                MessageBoxButtons.OK, MessageBoxIcon.Error);
        }
        finally
        {
            btnBuild.Enabled = true;
        }
    }

    // ── About ───────────────────────────────────────────────────

    private void btnAbout_Click(object? sender, EventArgs e)
    {
        using var dlg = new Form
        {
            Text = "About JeisAlive",
            StartPosition = FormStartPosition.CenterParent,
            FormBorderStyle = FormBorderStyle.FixedDialog,
            MaximizeBox = false,
            MinimizeBox = false,
            BackColor = Color.White,
            AutoSize = true,
            AutoSizeMode = AutoSizeMode.GrowAndShrink
        };

        // Use a TableLayoutPanel for proper DPI-aware layout
        var layout = new TableLayoutPanel
        {
            Dock = DockStyle.Fill,
            ColumnCount = 1,
            Padding = new Padding(20),
            AutoSize = true
        };
        layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));

        var pic = new PictureBox
        {
            Size = new Size(80, 80),
            SizeMode = PictureBoxSizeMode.StretchImage,
            BackColor = Color.LightGray,
            Anchor = AnchorStyles.None
        };
        try
        {
            using var client = new System.Net.Http.HttpClient();
            var data = client.GetByteArrayAsync("https://avatars.githubusercontent.com/u/185858215?v=4").Result;
            using var ms = new MemoryStream(data);
            pic.Image = Image.FromStream(ms);
        }
        catch { }

        var lblName = new Label
        {
            Text = "JeisAlive",
            Font = new Font("Segoe UI", 16F, FontStyle.Bold),
            ForeColor = Color.Black,
            AutoSize = true,
            Anchor = AnchorStyles.None
        };

        var lblAuthor = new Label
        {
            Text = "Made by gothyo",
            Font = new Font("Segoe UI", 11F, FontStyle.Regular),
            ForeColor = Color.FromArgb(80, 80, 80),
            AutoSize = true,
            Anchor = AnchorStyles.None
        };

        var lnkGithub = new LinkLabel
        {
            Text = "github.com/mysterygothic",
            Font = new Font("Segoe UI", 10F, FontStyle.Regular),
            AutoSize = true,
            Anchor = AnchorStyles.None,
            LinkColor = Color.FromArgb(0, 120, 212)
        };
        lnkGithub.Click += (_, _) =>
        {
            System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
            {
                FileName = "https://github.com/mysterygothic",
                UseShellExecute = true
            });
        };

        var btnOk = new Button
        {
            Text = "OK",
            Size = new Size(100, 35),
            DialogResult = DialogResult.OK,
            FlatStyle = FlatStyle.Flat,
            BackColor = Color.FromArgb(0, 120, 212),
            ForeColor = Color.White,
            Font = new Font("Segoe UI", 10F, FontStyle.Bold),
            Anchor = AnchorStyles.None
        };

        layout.RowCount = 5;
        layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));

        layout.Controls.Add(pic, 0, 0);
        layout.Controls.Add(lblName, 0, 1);
        layout.Controls.Add(lblAuthor, 0, 2);
        layout.Controls.Add(lnkGithub, 0, 3);
        layout.Controls.Add(btnOk, 0, 4);

        dlg.Controls.Add(layout);
        dlg.AcceptButton = btnOk;
        dlg.ShowDialog(this);
    }

    // ── Helpers ─────────────────────────────────────────────────

    private void AppendLog(string msg)
    {
        if (InvokeRequired)
        {
            Invoke(() => AppendLog(msg));
            return;
        }

        txtLog.AppendText(msg + "\r\n");
    }

    private void SetProgress(int value)
    {
        if (InvokeRequired)
        {
            Invoke(() => SetProgress(value));
            return;
        }

        prgProgress.Value = Math.Clamp(value, 0, 100);
    }
}
